language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

jobs:
  allow_failures:
  - python: "2.7"

install: 
  - pip install numpy cython 
  - pip install smt salib openturns
  - pip install -e .
  - pip list

script:
  - pytest
